### ISSUE TITLE
Is it editable if for Taiwan display?

### ISSUE THREAD

**Issue by AM-young-fun** [driaug/react-country-selector#7]
There're always political reasons to handle.  :<

**Comment by driaug** [comment]
This project uses the official country codes specified by the United Nations (https://unece.org/trade/cefact/unlocode-code-list-country-and-territory). You can always change, remove or add countries/regions to the [list](https://github.com/driaug/react-country-selector/blob/main/lib/countries.ts)

**Comment by AM-young-fun** [comment]
Thanks
