### ISSUE TITLE
No license provided

### ISSUE THREAD

**Issue by Anthony-Gaudino** [driaug/react-country-selector#8]
Hi, I noticed that your project doesn't provide a license.
If no license is provided this means that your code is not open sourced and could not be used / modified.
Please see https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by karilint** [comment]
I agree, a license would be great.

**Comment by driaug** [comment]
Consider it unlicensed.
